import React, { useState } from 'react';
import {
  Database,
  ExternalLink,
  CheckCircle2,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  RefreshCw,
  Server,
  ShieldCheck,
  Sparkles,
  KeyRound,
  Layers,
  Lock,
  Check,
  Copy,
  FileCode,
  Building2,
  User,
  Image as ImageIcon,
  CheckCheck,
} from 'lucide-react';
import { api } from '../utils/apiBridge';
import { copyToClipboard } from '../utils/clipboard';

interface DatabaseSetupWizardProps {
  companyName?: string;
  onSetupComplete: () => void;
}

interface StepProgressItem {
  stepKey: string;
  title: string;
  status: 'pending' | 'in_progress' | 'success' | 'failed' | 'skipped';
  message?: string;
}

const DEFAULT_STEPS: StepProgressItem[] = [
  { stepKey: 'connect_supabase', title: 'الاتصال بـ Supabase', status: 'pending', message: 'بانتظار التحقق من الاتصال...' },
  { stepKey: 'create_tables', title: 'إنشاء الجداول', status: 'pending', message: 'بانتظار التحقق من الجداول...' },
  { stepKey: 'create_relationships', title: 'إنشاء العلاقات', status: 'pending', message: 'بانتظار تدقيق العلاقات والمفاتيح الأجنبية...' },
  { stepKey: 'setup_permissions', title: 'إعداد الصلاحيات', status: 'pending', message: 'بانتظار فحص سياسات الأمان RLS...' },
  { stepKey: 'seed_initial_data', title: 'إعداد البيانات الأساسية', status: 'pending', message: 'بانتظار تهيئة سجلات الشركة والمدير...' },
  { stepKey: 'verify_database', title: 'التحقق من قاعدة البيانات', status: 'pending', message: 'بانتظار الفحص النهائي وتأكيد الجاهزية...' },
];

export const DatabaseSetupWizard: React.FC<DatabaseSetupWizardProps> = ({
  companyName = 'الشركة',
  onSetupComplete,
}) => {
  const [currentStep, setCurrentStep] = useState<1 | 2 | 3 | 4 | 5>(1);
  const [supabaseUrl, setSupabaseUrl] = useState('');
  const [supabaseAnonKey, setSupabaseAnonKey] = useState('');
  const [deviceName, setDeviceName] = useState('جهاز الإدارة الرئيسي');

  // Connection testing state
  const [isTesting, setIsTesting] = useState(false);
  const [testResult, setTestResult] = useState<{
    success: boolean;
    message: string;
    latencyMs?: number;
  } | null>(null);

  // Provisioning state
  const [isProvisioning, setIsProvisioning] = useState(false);
  const [provisioningProgress, setProvisioningProgress] = useState<StepProgressItem[]>(DEFAULT_STEPS);
  const [provisioningError, setProvisioningError] = useState<string | null>(null);

  // Step 4: Company & Admin Setup form state
  const [formCompanyName, setFormCompanyName] = useState(companyName || 'شركة الفعاليات');
  const [formCompanyLogo, setFormCompanyLogo] = useState('');
  const [formAdminFullName, setFormAdminFullName] = useState(`مدير ${companyName || 'الشركة'}`);
  const [formAdminUsername, setFormAdminUsername] = useState('admin');
  const [formAdminPassword, setFormAdminPassword] = useState('admin123');
  const [formAdminConfirmPassword, setFormAdminConfirmPassword] = useState('admin123');
  const [formError, setFormError] = useState<string | null>(null);
  const [isSavingCompany, setIsSavingCompany] = useState(false);

  // Step 5: Final Verification state
  const [verificationResult, setVerificationResult] = useState<{
    success: boolean;
    checks: {
      licenseValid: boolean;
      supabaseConnected: boolean;
      databaseProvisioned: boolean;
      companyExists: boolean;
      adminExists: boolean;
      subscriptionActive: boolean;
      schemaVersionValid: boolean;
    };
    companyName?: string;
    adminUsername?: string;
  } | null>(null);

  const [copiedField, setCopiedField] = useState<string | null>(null);
  const [copiedSql, setCopiedSql] = useState(false);

  const handleOpenSupabase = async (subPath: string = 'dashboard') => {
    try {
      await api.openExternalUrl(`https://supabase.com/${subPath}`);
    } catch {
      window.open(`https://supabase.com/${subPath}`, '_blank');
    }
  };

  const handleCopy = async (text: string, fieldName: string) => {
    const ok = await copyToClipboard(text);
    if (ok) {
      setCopiedField(fieldName);
      setTimeout(() => setCopiedField(null), 2500);
    }
  };

  const handleCopySchemaSql = async () => {
    const schemaSql = `-- ==============================================================================
-- مخطط قاعدة بيانات Supabase لنظام إدارة الفعاليات والدعوات (Dedicated Perpetual)
-- ==============================================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    logo_url TEXT,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    created_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    temp_password TEXT,
    full_name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'EMPLOYEE',
    must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    date TEXT NOT NULL,
    capacity INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    time TEXT,
    venue TEXT,
    "eventType" TEXT DEFAULT 'wedding',
    created_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    updated_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE IF NOT EXISTS invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    invitation_number INTEGER NOT NULL,
    token TEXT NOT NULL UNIQUE,
    guest_name TEXT,
    graduate_name TEXT,
    has_name INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'UNUSED',
    created_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    used_at TEXT
);

CREATE TABLE IF NOT EXISTS scan_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invitation_id BIGINT REFERENCES invitations(id) ON DELETE SET NULL,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    scanned_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    result TEXT NOT NULL,
    device_name TEXT,
    scanned_by_name TEXT,
    scanned_by_id BIGINT REFERENCES app_users(id) ON DELETE SET NULL,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS tenant_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT UNIQUE NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    plan_name TEXT NOT NULL DEFAULT 'Professional',
    billing_cycle TEXT NOT NULL DEFAULT 'lifetime',
    status TEXT NOT NULL DEFAULT 'active',
    start_date TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    renewal_date TEXT NOT NULL DEFAULT to_char(NOW() + interval '100 year', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    expiration_date TEXT NOT NULL DEFAULT to_char(NOW() + interval '100 year', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    payment_status TEXT NOT NULL DEFAULT 'paid',
    created_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    updated_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE IF NOT EXISTS database_schema_version (
    version INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    applied_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE INDEX IF NOT EXISTS idx_app_users_username ON app_users(username);
CREATE INDEX IF NOT EXISTS idx_app_users_company ON app_users(company_id);
CREATE INDEX IF NOT EXISTS idx_events_company ON events(company_id);
CREATE INDEX IF NOT EXISTS idx_invitations_token ON invitations(token);
CREATE INDEX IF NOT EXISTS idx_invitations_event ON invitations(event_id);
CREATE INDEX IF NOT EXISTS idx_invitations_status ON invitations(status);
CREATE INDEX IF NOT EXISTS idx_scan_logs_event ON scan_logs(event_id);
CREATE INDEX IF NOT EXISTS idx_scan_logs_scanned_at ON scan_logs(scanned_at DESC);
CREATE INDEX IF NOT EXISTS idx_subscriptions_company ON tenant_subscriptions(company_id);

CREATE OR REPLACE FUNCTION login_app_user(p_username TEXT, p_password TEXT)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_user RECORD;
    v_input_hash TEXT;
BEGIN
    v_input_hash := encode(digest(TRIM(p_password), 'sha256'), 'hex');
    SELECT u.*, c.name as comp_name, c.logo_url as comp_logo, c.status as comp_status,
           s.status as sub_status, s.expiration_date as sub_expiration, s.plan_name as sub_plan
    INTO v_user
    FROM app_users u
    LEFT JOIN companies c ON u.company_id = c.id
    LEFT JOIN tenant_subscriptions s ON s.company_id = c.id
    WHERE LOWER(TRIM(u.username)) = LOWER(TRIM(p_username));

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'error', 'اسم المستخدم غير موجود');
    END IF;

    IF v_user.password_hash <> v_input_hash AND (v_user.temp_password IS NULL OR v_user.temp_password <> TRIM(p_password)) THEN
        RETURN jsonb_build_object('success', false, 'error', 'كلمة المرور غير صحيحة');
    END IF;

    IF v_user.role <> 'SUPER_ADMIN' THEN
        IF v_user.comp_status = 'SUSPENDED' OR v_user.comp_status = 'INACTIVE' THEN
            RETURN jsonb_build_object('success', false, 'error', 'يرجى التواصل مع الإدارة');
        END IF;
    END IF;

    RETURN jsonb_build_object(
        'success', true,
        'user', jsonb_build_object(
            'id', v_user.id,
            'company_id', v_user.company_id,
            'username', v_user.username,
            'full_name', v_user.full_name,
            'role', v_user.role,
            'must_change_password', v_user.must_change_password,
            'temp_password', v_user.temp_password,
            'company_name', v_user.comp_name,
            'company_logo', v_user.comp_logo,
            'company_status', v_user.comp_status,
            'subscription_status', v_user.sub_status
        )
    );
END;
$$;

CREATE OR REPLACE FUNCTION check_in_atomic(p_token TEXT, p_event_id BIGINT, p_device_name TEXT DEFAULT NULL, p_scanned_by TEXT DEFAULT NULL)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_inv RECORD;
    v_now TEXT := to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
    v_prev_scan RECORD;
    v_scanner_label TEXT := COALESCE(NULLIF(TRIM(p_scanned_by), ''), 'الموظف المسؤول');
BEGIN
    SELECT * INTO v_inv FROM invitations WHERE token = TRIM(p_token) FOR UPDATE;

    IF NOT FOUND THEN
        INSERT INTO scan_logs (invitation_id, event_id, scanned_at, result, device_name, scanned_by_name, notes)
        VALUES (NULL, p_event_id, v_now, 'INVALID', p_device_name, v_scanner_label, 'رمز QR غير معروف');
        RETURN jsonb_build_object('success', false, 'result', 'INVALID', 'message', 'رمز الدعوة غير صالح أو غير موجود في النظام!');
    END IF;

    IF v_inv.event_id <> p_event_id THEN
        INSERT INTO scan_logs (invitation_id, event_id, scanned_at, result, device_name, scanned_by_name, notes)
        VALUES (v_inv.id, p_event_id, v_now, 'WRONG_EVENT', p_device_name, v_scanner_label, 'دعوة تابعة لمناسبة أخرى');
        RETURN jsonb_build_object('success', false, 'result', 'WRONG_EVENT', 'message', 'هذه الدعوة مخصصة لمناسبة أخرى!', 'guestName', v_inv.guest_name, 'invitationNumber', v_inv.invitation_number);
    END IF;

    IF v_inv.status = 'USED' THEN
        SELECT scanned_by_name, scanned_at INTO v_prev_scan FROM scan_logs WHERE invitation_id = v_inv.id AND result = 'ACCEPTED' ORDER BY id DESC LIMIT 1;
        INSERT INTO scan_logs (invitation_id, event_id, scanned_at, result, device_name, scanned_by_name, notes)
        VALUES (v_inv.id, p_event_id, v_now, 'ALREADY_USED', p_device_name, v_scanner_label, 'محاولة دخول مكررة لدعوة مستخدمة مسبقاً');
        RETURN jsonb_build_object('success', false, 'result', 'ALREADY_USED', 'message', 'تم استخدام هذه الدعوة مسبقاً!', 'previousUsedAt', COALESCE(v_prev_scan.scanned_at, v_inv.used_at), 'scannedBy', v_prev_scan.scanned_by_name, 'guestName', v_inv.guest_name, 'invitationNumber', v_inv.invitation_number);
    END IF;

    UPDATE invitations SET status = 'USED', used_at = v_now WHERE id = v_inv.id AND status = 'UNUSED';

    INSERT INTO scan_logs (invitation_id, event_id, scanned_at, result, device_name, scanned_by_name, notes)
    VALUES (v_inv.id, p_event_id, v_now, 'ACCEPTED', p_device_name, v_scanner_label, 'دخول مصرح - الدعوة #' || v_inv.invitation_number);

    RETURN jsonb_build_object('success', true, 'result', 'ACCEPTED', 'message', 'تم قبول الدخول بنجاح.', 'guestName', v_inv.guest_name, 'invitationNumber', v_inv.invitation_number, 'scannedBy', v_scanner_label, 'used_at', v_now);
END;
$$;

ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE scan_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE database_schema_version ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for companies" ON companies;
CREATE POLICY "Allow all for companies" ON companies FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow all for app_users" ON app_users;
CREATE POLICY "Allow all for app_users" ON app_users FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow all for events" ON events;
CREATE POLICY "Allow all for events" ON events FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow all for invitations" ON invitations;
CREATE POLICY "Allow all for invitations" ON invitations FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow all for scan_logs" ON scan_logs;
CREATE POLICY "Allow all for scan_logs" ON scan_logs FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow all for tenant_subscriptions" ON tenant_subscriptions;
CREATE POLICY "Allow all for tenant_subscriptions" ON tenant_subscriptions FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow all for database_schema_version" ON database_schema_version;
CREATE POLICY "Allow all for database_schema_version" ON database_schema_version FOR ALL USING (true) WITH CHECK (true);

INSERT INTO database_schema_version (version, name) VALUES (1, 'v1_initial_core_schema') ON CONFLICT (version) DO NOTHING;
`;

    const ok = await copyToClipboard(schemaSql);
    if (ok) {
      setCopiedSql(true);
      setTimeout(() => setCopiedSql(false), 3000);
    }
  };

  const handleTestConnection = async () => {
    const cleanUrl = supabaseUrl.trim();
    const cleanKey = supabaseAnonKey.trim();

    if (!cleanUrl || !cleanKey) {
      setTestResult({
        success: false,
        message: 'يرجى إدخال رابط المشروع ومفتاح Anon أولاً.',
      });
      return;
    }

    setIsTesting(true);
    setTestResult(null);

    try {
      const res = await api.testCloudConnection(cleanUrl, cleanKey);
      setTestResult({
        success: res.success,
        message:
          res.message ||
          (res.success ? '✓ تم الاتصال بقاعدة البيانات بنجاح' : 'تعذر الاتصال بمشروع Supabase'),
        latencyMs: res.latencyMs,
      });
    } catch (err: any) {
      setTestResult({
        success: false,
        message: err.message || 'حدث خطأ أثناء اختبار الاتصال بالخادم السحابي.',
      });
    } finally {
      setIsTesting(false);
    }
  };

  const handleStartProvisioning = async () => {
    const cleanUrl = supabaseUrl.trim();
    const cleanKey = supabaseAnonKey.trim();

    if (!cleanUrl || !cleanKey) {
      setTestResult({
        success: false,
        message: 'يرجى إدخال رابط المشروع ومفتاح Anon أولاً.',
      });
      return;
    }

    setCurrentStep(3);
    setIsProvisioning(true);
    setProvisioningError(null);
    setProvisioningProgress(
      DEFAULT_STEPS.map((s, idx) => ({
        ...s,
        status: idx === 0 ? 'in_progress' : 'pending',
        message: idx === 0 ? 'جاري التحقق من الاتصال بمشروع Supabase...' : s.message,
      }))
    );

    try {
      const res = await api.provisionDedicatedDatabase({
        supabaseUrl: cleanUrl,
        supabaseAnonKey: cleanKey,
        companyName: formCompanyName.trim() || companyName,
        deviceName: deviceName.trim(),
      });

      if (res.steps && res.steps.length > 0) {
        setProvisioningProgress(res.steps as StepProgressItem[]);
      }

      if (res.success) {
        // Database provisioned successfully -> move to Step 4 (Company & Admin Setup)
        setTimeout(() => {
          setCurrentStep(4);
        }, 800);
      } else {
        setProvisioningError(
          res.error || 'تعذر تجهيز قاعدة البيانات. يرجى مراجعة الخطوات والمحاولة مجدداً.'
        );
      }
    } catch (err: any) {
      setProvisioningError(err.message || 'حدث خطأ غير متوقع أثناء عملية التجهيز.');
    } finally {
      setIsProvisioning(false);
    }
  };

  const handleSaveCompanyAndAdmin = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);

    const cleanCompany = formCompanyName.trim();
    const cleanFullName = formAdminFullName.trim();
    const cleanUsername = formAdminUsername.trim();
    const cleanPassword = formAdminPassword.trim();
    const cleanConfirm = formAdminConfirmPassword.trim();

    if (!cleanCompany) {
      setFormError('يرجى إدخال اسم الشركة أو المنظمة.');
      return;
    }
    if (!cleanFullName) {
      setFormError('يرجى إدخال الاسم الكامل للمدير المسؤول.');
      return;
    }
    if (!cleanUsername || cleanUsername.length < 3) {
      setFormError('اسم المستخدم يجب أن يتكون من 3 أحرف على الأقل.');
      return;
    }
    if (!cleanPassword || cleanPassword.length < 4) {
      setFormError('كلمة المرور يجب ألا تقل عن 4 خانات.');
      return;
    }
    if (cleanPassword !== cleanConfirm) {
      setFormError('كلمة المرور وتأكيدها غير متطابقين.');
      return;
    }

    setIsSavingCompany(true);

    try {
      // 1. Setup Company, Admin & Perpetual Subscription
      const res = await api.setupDedicatedCompanyAndAdmin({
        supabaseUrl: supabaseUrl.trim(),
        supabaseAnonKey: supabaseAnonKey.trim(),
        companyName: cleanCompany,
        logoUrl: formCompanyLogo.trim() || null,
        adminFullName: cleanFullName,
        adminUsername: cleanUsername,
        adminPassword: cleanPassword,
        deviceName: deviceName.trim(),
      });

      if (!res.success) {
        setFormError(res.error || 'فشل حفظ إعدادات الشركة وحساب المدير.');
        setIsSavingCompany(false);
        return;
      }

      // 2. Perform Complete Verification
      const verifyRes = await api.verifyDedicatedInstallation({
        supabaseUrl: supabaseUrl.trim(),
        supabaseAnonKey: supabaseAnonKey.trim(),
      });

      setVerificationResult({
        success: verifyRes.success,
        checks: verifyRes.checks,
        companyName: verifyRes.companyName || cleanCompany,
        adminUsername: verifyRes.adminUsername || cleanUsername,
      });

      // Move to Step 5 (Final Verification & Success)
      setCurrentStep(5);
    } catch (err: any) {
      setFormError(err.message || 'حدث خطأ غير متوقع أثناء حفظ الإعدادات.');
    } finally {
      setIsSavingCompany(false);
    }
  };

  const handleLogoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (file.size > 2 * 1024 * 1024) {
        setFormError('حجم الصورة كبير جداً، يرجى اختيار صورة أقل من 2 ميجابايت.');
        return;
      }
      const reader = new FileReader();
      reader.onload = () => {
        if (typeof reader.result === 'string') {
          setFormCompanyLogo(reader.result);
        }
      };
      reader.readAsDataURL(file);
    }
  };

  return (
    <div className="min-h-screen w-full bg-slate-950 text-white flex flex-col justify-center items-center p-4 sm:p-6 relative overflow-hidden font-arabic selection:bg-amber-500 selection:text-slate-950">
      {/* Ambient background glow */}
      <div className="absolute top-1/4 -right-28 w-96 h-96 bg-amber-500/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-1/4 -left-28 w-96 h-96 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute inset-0 bg-[radial-gradient(#1e293b_1px,transparent_1px)] [background-size:24px_24px] opacity-25 pointer-events-none" />

      {/* Main Setup Container */}
      <div className="relative w-full max-w-2xl bg-slate-900/90 border border-slate-800 rounded-3xl p-6 sm:p-8 shadow-2xl backdrop-blur-xl animate-in fade-in zoom-in-95 duration-300">
        {/* Step Indicator Header */}
        <div className="flex items-center justify-between border-b border-slate-800 pb-5 mb-6">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-amber-500 via-amber-400 to-amber-300 flex items-center justify-center shadow-lg shadow-amber-500/20">
              <Database className="w-6 h-6 text-slate-950 stroke-[2.5]" />
            </div>
            <div>
              <div className="flex items-center gap-1.5 text-xs text-amber-400 font-bold">
                <Sparkles className="w-3.5 h-3.5" />
                <span>إعداد التثبيت المستقل • {formCompanyName || companyName}</span>
              </div>
              <h1 className="text-xl sm:text-2xl font-black text-white">
                {currentStep === 4 ? 'إعداد الشركة والمسؤول' : currentStep === 5 ? 'اكتمال إعداد النظام' : 'ربط وتجهيز قاعدة البيانات'}
              </h1>
            </div>
          </div>

          {/* Stepper dots */}
          <div className="flex items-center gap-2" dir="ltr">
            {[1, 2, 3, 4, 5].map((stepNum) => (
              <div
                key={stepNum}
                className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold transition-all duration-300 ${
                  currentStep === stepNum
                    ? 'bg-amber-400 text-slate-950 ring-4 ring-amber-400/20 scale-110 font-black'
                    : currentStep > stepNum
                    ? 'bg-emerald-500 text-white'
                    : 'bg-slate-800 text-slate-400'
                }`}
              >
                {currentStep > stepNum ? <Check className="w-3.5 h-3.5 stroke-[3]" /> : stepNum}
              </div>
            ))}
          </div>
        </div>

        {/* STEP 1: Supabase Project Creation Instructions */}
        {currentStep === 1 && (
          <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-200">
            <div className="p-4 rounded-2xl bg-amber-500/10 border border-amber-500/20 text-amber-200 text-xs sm:text-sm leading-relaxed flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
              <div>
                <p className="font-bold text-amber-300 mb-1">
                  مشروع Supabase مخصص ومستقل لشركتكم:
                </p>
                <p className="text-xs text-slate-300 leading-relaxed">
                  تتطلب نسخة الشراء الدائم (Dedicated) ربط مشروع Supabase سحابي خاص بشركتكم لضمان
                  حفظ وتخزين جميع بيانات الفعاليات والدعوات وسجلات المسح في خادمكم الخاص مع تحكم
                  كامل وأمان تام.
                </p>
              </div>
            </div>

            <div className="space-y-3">
              <h3 className="text-sm font-bold text-slate-200 flex items-center gap-2">
                <Layers className="w-4 h-4 text-amber-400" />
                <span>خطوات تجهيز مشروع Supabase:</span>
              </h3>

              <div className="grid gap-2.5 text-xs text-slate-300">
                <div className="p-3 rounded-2xl bg-slate-950/70 border border-slate-800/80 flex items-start gap-3">
                  <span className="w-5 h-5 rounded-full bg-slate-800 text-amber-400 font-bold flex items-center justify-center shrink-0 mt-0.5">
                    1
                  </span>
                  <div>
                    <span className="font-bold text-white">افتح موقع Supabase:</span> اضغط على زر
                    "فتح Supabase" بالأسفل لإنشاء حساب مجاني أو تسجيل الدخول.
                  </div>
                </div>

                <div className="p-3 rounded-2xl bg-slate-950/70 border border-slate-800/80 flex items-start gap-3">
                  <span className="w-5 h-5 rounded-full bg-slate-800 text-amber-400 font-bold flex items-center justify-center shrink-0 mt-0.5">
                    2
                  </span>
                  <div>
                    <span className="font-bold text-white">أنشئ مشروعاً جديداً (New Project):</span>{' '}
                    اختر اسماً للمشروع (مثل: {companyName}) واختر كلمة مرور قوية لقاعدة البيانات.
                  </div>
                </div>

                <div className="p-3 rounded-2xl bg-slate-950/70 border border-slate-800/80 flex items-start gap-3">
                  <span className="w-5 h-5 rounded-full bg-slate-800 text-amber-400 font-bold flex items-center justify-center shrink-0 mt-0.5">
                    3
                  </span>
                  <div>
                    <span className="font-bold text-white">انسخ بيانات الربط:</span> من القائمة
                    الجانبية توجه إلى{' '}
                    <code className="bg-slate-900 text-amber-300 px-1.5 py-0.5 rounded font-mono" dir="ltr">
                      Project Settings &gt; API
                    </code>{' '}
                    لنسخ رابط المشروع (Project URL) ومفتاح anon العام.
                  </div>
                </div>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="pt-2 flex flex-col sm:flex-row items-center gap-3">
              <button
                type="button"
                onClick={() => handleOpenSupabase('dashboard')}
                className="w-full sm:w-1/2 py-3.5 px-4 rounded-2xl font-bold text-xs sm:text-sm bg-slate-800 hover:bg-slate-700 text-white border border-slate-700 hover:border-slate-600 flex items-center justify-center gap-2 cursor-pointer transition-all duration-200"
              >
                <ExternalLink className="w-4 h-4 text-emerald-400" />
                <span>فتح Supabase</span>
              </button>

              <button
                type="button"
                onClick={() => setCurrentStep(2)}
                className="w-full sm:w-1/2 py-3.5 px-4 rounded-2xl font-bold text-xs sm:text-sm bg-gradient-to-r from-amber-500 to-amber-400 hover:from-amber-400 hover:to-amber-300 text-slate-950 shadow-lg shadow-amber-500/20 flex items-center justify-center gap-2 cursor-pointer transition-all duration-200"
              >
                <span>المتابعة وإدخال المفاتيح</span>
                <ArrowLeft className="w-4 h-4 stroke-[2.5]" />
              </button>
            </div>
          </div>
        )}

        {/* STEP 2: Input URL & Publishable Anon Key */}
        {currentStep === 2 && (
          <div className="space-y-4 animate-in fade-in slide-in-from-right-4 duration-200">
            {/* Security Guarantee Notice */}
            <div className="p-3.5 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-300 text-xs flex items-center gap-2.5">
              <Lock className="w-4 h-4 text-emerald-400 shrink-0" />
              <span>
                🔒 <strong>أمان مضمون:</strong> يطلب النظام مفتاح الوصول العام (Anon Key) فقط، ولا
                يطلب أو يخزن كلمة مرور قاعدة البيانات أو مفتاح Service Role السري.
              </span>
            </div>

            {/* Project URL */}
            <div className="space-y-1.5 text-right">
              <label className="text-xs font-bold text-slate-300 flex items-center justify-end gap-1.5">
                <span>رابط مشروع Supabase الخاص بالشركة (Project URL)</span>
                <Server className="w-3.5 h-3.5 text-amber-400" />
              </label>
              <input
                type="text"
                value={supabaseUrl}
                onChange={(e) => {
                  setSupabaseUrl(e.target.value);
                  setTestResult(null);
                }}
                placeholder="https://your-project-ref.supabase.co"
                dir="ltr"
                required
                className="w-full bg-slate-950/80 border border-slate-800 focus:border-amber-400 focus:ring-1 focus:ring-amber-400/30 rounded-2xl px-4 py-3 text-xs sm:text-sm text-white font-mono placeholder-slate-600 outline-none transition-all duration-200"
              />
            </div>

            {/* Anon Key */}
            <div className="space-y-1.5 text-right">
              <div className="flex items-center justify-between">
                <button
                  type="button"
                  onClick={handleTestConnection}
                  disabled={isTesting || !supabaseUrl.trim() || !supabaseAnonKey.trim()}
                  className="text-xs font-bold text-emerald-400 hover:text-emerald-300 flex items-center gap-1.5 disabled:opacity-50 transition-colors cursor-pointer"
                >
                  <RefreshCw className={`w-3.5 h-3.5 ${isTesting ? 'animate-spin' : ''}`} />
                  <span>[ اختبار الاتصال ]</span>
                </button>
                <label className="text-xs font-bold text-slate-300 flex items-center gap-1.5">
                  <span>مفتاح Supabase العام (Anon / Publishable Key)</span>
                  <KeyRound className="w-3.5 h-3.5 text-amber-400" />
                </label>
              </div>
              <textarea
                rows={2}
                value={supabaseAnonKey}
                onChange={(e) => {
                  setSupabaseAnonKey(e.target.value);
                  setTestResult(null);
                }}
                placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                dir="ltr"
                required
                className="w-full bg-slate-950/80 border border-slate-800 focus:border-amber-400 focus:ring-1 focus:ring-amber-400/30 rounded-2xl px-4 py-2.5 text-xs text-white font-mono placeholder-slate-600 outline-none transition-all duration-200 resize-none"
              />
            </div>

            {/* Test Connection Feedback Badge */}
            {testResult && (
              <div
                className={`p-3 rounded-2xl border text-xs flex items-center gap-2.5 animate-in fade-in duration-200 ${
                  testResult.success
                    ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-300'
                    : 'bg-rose-500/10 border-rose-500/30 text-rose-300'
                }`}
              >
                {testResult.success ? (
                  <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                ) : (
                  <AlertCircle className="w-4 h-4 text-rose-400 shrink-0" />
                )}
                <div className="flex-1 text-right leading-relaxed">
                  <span>{testResult.message}</span>
                  {testResult.latencyMs !== undefined && testResult.latencyMs > 0 && (
                    <span className="text-[10px] text-slate-400 block mt-0.5" dir="ltr">
                      Latency: {testResult.latencyMs}ms
                    </span>
                  )}
                </div>
              </div>
            )}

            {/* Navigation & Action Buttons */}
            <div className="pt-3 flex items-center gap-3">
              <button
                type="button"
                onClick={() => setCurrentStep(1)}
                className="py-3.5 px-4 rounded-2xl font-bold text-xs sm:text-sm bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 flex items-center justify-center gap-1.5 cursor-pointer transition-all duration-200"
              >
                <ArrowRight className="w-4 h-4" />
                <span>السابق</span>
              </button>

              <button
                type="button"
                onClick={handleStartProvisioning}
                disabled={!supabaseUrl.trim() || !supabaseAnonKey.trim()}
                className="flex-1 py-3.5 px-4 rounded-2xl font-bold text-xs sm:text-sm bg-gradient-to-r from-amber-500 to-amber-400 hover:from-amber-400 hover:to-amber-300 text-slate-950 shadow-lg shadow-amber-500/20 disabled:opacity-50 flex items-center justify-center gap-2 cursor-pointer transition-all duration-200"
              >
                <span>بدء تجهيز قاعدة البيانات</span>
                <ArrowLeft className="w-4 h-4 stroke-[2.5]" />
              </button>
            </div>
          </div>
        )}

        {/* STEP 3: Provisioning & Migration Progress Screen */}
        {currentStep === 3 && (
          <div className="space-y-5 animate-in fade-in slide-in-from-right-4 duration-200">
            <div className="text-center space-y-1">
              <h3 className="text-lg font-black text-white">
                {provisioningError ? 'تعذر تجهيز قاعدة البيانات' : 'جاري تجهيز قاعدة البيانات'}
              </h3>
              <p className="text-xs text-slate-400">
                {provisioningError
                  ? 'يرجى مراجعة الخطوات أدناه والمحاولة مجدداً'
                  : 'يقوم النظام بإنشاء الجداول وإعداد العلاقات والصلاحيات الأساسية'}
              </p>
            </div>

            {/* 6 Steps Progress List */}
            <div className="space-y-2 p-4 rounded-2xl bg-slate-950/80 border border-slate-800">
              {provisioningProgress.map((item, idx) => (
                <div
                  key={idx}
                  className="flex items-center justify-between text-xs py-2 border-b border-slate-900/80 last:border-none"
                >
                  <div className="flex items-center gap-3">
                    {item.status === 'success' && (
                      <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 stroke-[2.5]" />
                    )}
                    {item.status === 'in_progress' && (
                      <RefreshCw className="w-4 h-4 text-amber-400 animate-spin shrink-0 stroke-[2.5]" />
                    )}
                    {item.status === 'failed' && (
                      <AlertCircle className="w-4 h-4 text-rose-400 shrink-0 stroke-[2.5]" />
                    )}
                    {item.status === 'pending' && (
                      <div className="w-4 h-4 rounded-full border border-slate-700 shrink-0" />
                    )}
                    <div className="text-right">
                      <div
                        className={`font-bold ${
                          item.status === 'success'
                            ? 'text-emerald-300'
                            : item.status === 'failed'
                            ? 'text-rose-300'
                            : item.status === 'in_progress'
                            ? 'text-amber-300'
                            : 'text-slate-400'
                        }`}
                      >
                        {item.title}
                      </div>
                      {item.message && (
                        <div className="text-[11px] text-slate-400 mt-0.5">{item.message}</div>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* Error Actions & SQL Helper */}
            {provisioningError && (
              <div className="p-4 rounded-2xl bg-rose-500/10 border border-rose-500/30 text-rose-200 text-xs space-y-3 animate-in fade-in">
                <div className="flex items-start gap-2.5">
                  <AlertCircle className="w-4 h-4 text-rose-400 shrink-0 mt-0.5" />
                  <div className="leading-relaxed text-slate-200">{provisioningError}</div>
                </div>

                <div className="pt-2 border-t border-rose-500/20 flex flex-wrap items-center gap-2">
                  <button
                    type="button"
                    onClick={handleStartProvisioning}
                    disabled={isProvisioning}
                    className="px-4 py-2 rounded-xl bg-amber-400 hover:bg-amber-300 text-slate-950 font-black text-xs shadow-md shadow-amber-400/20 flex items-center gap-1.5 cursor-pointer disabled:opacity-50 transition-all"
                  >
                    <RefreshCw className={`w-3.5 h-3.5 ${isProvisioning ? 'animate-spin' : ''}`} />
                    <span>[ إعادة المحاولة ]</span>
                  </button>

                  <button
                    type="button"
                    onClick={handleCopySchemaSql}
                    className="px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 font-bold text-xs border border-slate-700 flex items-center gap-1.5 cursor-pointer transition-all"
                  >
                    {copiedSql ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-emerald-400" />
                        <span className="text-emerald-400 font-black">تم نسخ كود SQL كامل</span>
                      </>
                    ) : (
                      <>
                        <FileCode className="w-3.5 h-3.5 text-amber-400" />
                        <span>نسخ كود إنشاء الجداول (SQL Schema)</span>
                      </>
                    )}
                  </button>

                  <button
                    type="button"
                    onClick={() => handleOpenSupabase('dashboard')}
                    className="px-3.5 py-2 rounded-xl bg-emerald-500/20 text-emerald-300 hover:bg-emerald-500/30 font-bold text-xs border border-emerald-500/30 flex items-center gap-1.5 cursor-pointer transition-all"
                  >
                    <ExternalLink className="w-3.5 h-3.5" />
                    <span>فتح SQL Editor</span>
                  </button>
                </div>
              </div>
            )}
          </div>
        )}

        {/* STEP 4: Company & Admin Setup Screen */}
        {currentStep === 4 && (
          <form onSubmit={handleSaveCompanyAndAdmin} className="space-y-4 animate-in fade-in slide-in-from-right-4 duration-200">
            <div className="text-center space-y-1 mb-4">
              <h3 className="text-lg font-black text-white flex items-center justify-center gap-2">
                <Building2 className="w-5 h-5 text-amber-400" />
                <span>إعداد الشركة وحساب المدير</span>
              </h3>
              <p className="text-xs text-slate-400">
                أدخل بيانات المؤسسة والحساب الإداري الرئيسي للبدء في إدارة الفعاليات
              </p>
            </div>

            {formError && (
              <div className="p-3 rounded-2xl bg-rose-500/10 border border-rose-500/30 text-rose-300 text-xs flex items-center gap-2">
                <AlertCircle className="w-4 h-4 text-rose-400 shrink-0" />
                <span>{formError}</span>
              </div>
            )}

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5 text-right">
              {/* Company Name */}
              <div className="space-y-1.5 sm:col-span-2">
                <label className="text-xs font-bold text-slate-300 flex items-center justify-end gap-1.5">
                  <span>اسم الشركة / المنظمة</span>
                  <Building2 className="w-3.5 h-3.5 text-amber-400" />
                </label>
                <input
                  type="text"
                  required
                  value={formCompanyName}
                  onChange={(e) => setFormCompanyName(e.target.value)}
                  placeholder="مثال: شركة النخبة للمناسبات"
                  className="w-full bg-slate-950/80 border border-slate-800 focus:border-amber-400 focus:ring-1 focus:ring-amber-400/30 rounded-2xl px-4 py-2.5 text-xs sm:text-sm text-white outline-none transition-all"
                />
              </div>

              {/* Company Logo Upload / URL */}
              <div className="space-y-1.5 sm:col-span-2">
                <label className="text-xs font-bold text-slate-300 flex items-center justify-end gap-1.5">
                  <span>شعار الشركة (اختياري)</span>
                  <ImageIcon className="w-3.5 h-3.5 text-amber-400" />
                </label>
                <div className="flex items-center gap-3">
                  {formCompanyLogo ? (
                    <div className="w-12 h-12 rounded-xl bg-slate-800 border border-slate-700 p-1 flex items-center justify-center shrink-0">
                      <img src={formCompanyLogo} alt="Logo" className="w-full h-full object-contain rounded-lg" />
                    </div>
                  ) : null}
                  <input
                    type="file"
                    accept="image/*"
                    onChange={handleLogoUpload}
                    className="flex-1 bg-slate-950/80 border border-slate-800 rounded-2xl px-3 py-2 text-xs text-slate-400 file:mr-2 file:py-1 file:px-3 file:rounded-xl file:border-0 file:text-xs file:font-bold file:bg-slate-800 file:text-amber-400 hover:file:bg-slate-700 cursor-pointer"
                  />
                </div>
              </div>

              {/* Admin Full Name */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-slate-300 flex items-center justify-end gap-1.5">
                  <span>الاسم الكامل للمدير</span>
                  <User className="w-3.5 h-3.5 text-amber-400" />
                </label>
                <input
                  type="text"
                  required
                  value={formAdminFullName}
                  onChange={(e) => setFormAdminFullName(e.target.value)}
                  placeholder="الاسم الثلاثي"
                  className="w-full bg-slate-950/80 border border-slate-800 focus:border-amber-400 focus:ring-1 focus:ring-amber-400/30 rounded-2xl px-4 py-2.5 text-xs sm:text-sm text-white outline-none transition-all"
                />
              </div>

              {/* Admin Username */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-slate-300 flex items-center justify-end gap-1.5">
                  <span>اسم المستخدم</span>
                  <KeyRound className="w-3.5 h-3.5 text-amber-400" />
                </label>
                <input
                  type="text"
                  required
                  value={formAdminUsername}
                  onChange={(e) => setFormAdminUsername(e.target.value)}
                  placeholder="admin"
                  dir="ltr"
                  className="w-full bg-slate-950/80 border border-slate-800 focus:border-amber-400 focus:ring-1 focus:ring-amber-400/30 rounded-2xl px-4 py-2.5 text-xs sm:text-sm text-white font-mono outline-none transition-all"
                />
              </div>

              {/* Admin Password */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-slate-300 flex items-center justify-end gap-1.5">
                  <span>كلمة المرور</span>
                  <Lock className="w-3.5 h-3.5 text-amber-400" />
                </label>
                <input
                  type="password"
                  required
                  value={formAdminPassword}
                  onChange={(e) => setFormAdminPassword(e.target.value)}
                  placeholder="••••••••"
                  className="w-full bg-slate-950/80 border border-slate-800 focus:border-amber-400 focus:ring-1 focus:ring-amber-400/30 rounded-2xl px-4 py-2.5 text-xs sm:text-sm text-white outline-none transition-all"
                />
              </div>

              {/* Admin Confirm Password */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-slate-300 flex items-center justify-end gap-1.5">
                  <span>تأكيد كلمة المرور</span>
                  <Lock className="w-3.5 h-3.5 text-amber-400" />
                </label>
                <input
                  type="password"
                  required
                  value={formAdminConfirmPassword}
                  onChange={(e) => setFormAdminConfirmPassword(e.target.value)}
                  placeholder="••••••••"
                  className="w-full bg-slate-950/80 border border-slate-800 focus:border-amber-400 focus:ring-1 focus:ring-amber-400/30 rounded-2xl px-4 py-2.5 text-xs sm:text-sm text-white outline-none transition-all"
                />
              </div>
            </div>

            {/* Action Buttons */}
            <div className="pt-3 flex items-center gap-3">
              <button
                type="button"
                onClick={() => setCurrentStep(2)}
                className="py-3.5 px-4 rounded-2xl font-bold text-xs sm:text-sm bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 flex items-center justify-center gap-1.5 cursor-pointer transition-all"
              >
                <ArrowRight className="w-4 h-4" />
                <span>السابق</span>
              </button>

              <button
                type="submit"
                disabled={isSavingCompany}
                className="flex-1 py-3.5 px-4 rounded-2xl font-bold text-xs sm:text-sm bg-gradient-to-r from-amber-500 to-amber-400 hover:from-amber-400 hover:to-amber-300 text-slate-950 shadow-lg shadow-amber-500/20 disabled:opacity-50 flex items-center justify-center gap-2 cursor-pointer transition-all"
              >
                {isSavingCompany ? (
                  <>
                    <RefreshCw className="w-4 h-4 animate-spin" />
                    <span>جاري حفظ الإعدادات والتحقق النهائي...</span>
                  </>
                ) : (
                  <>
                    <span>حفظ ومتابعة التحقق النهائي</span>
                    <ArrowLeft className="w-4 h-4 stroke-[2.5]" />
                  </>
                )}
              </button>
            </div>
          </form>
        )}

        {/* STEP 5: Final Verification & Success Screen */}
        {currentStep === 5 && (
          <div className="space-y-5 text-center animate-in fade-in zoom-in-95 duration-300">
            <div className="w-16 h-16 rounded-3xl bg-gradient-to-tr from-emerald-500 to-emerald-300 flex items-center justify-center mx-auto shadow-2xl shadow-emerald-500/20 animate-bounce">
              <CheckCheck className="w-9 h-9 text-slate-950 stroke-[2.5]" />
            </div>

            <div>
              <h2 className="text-xl sm:text-2xl font-black text-white">
                تم إعداد النظام بنجاح
              </h2>
              <p className="text-xs text-slate-400 mt-1">
                تم ربط قاعدة البيانات وتفعيل الترخيص الدائم وإعداد حساب المسؤول بنجاح تام
              </p>
            </div>

            {/* Verification Checklist */}
            <div className="p-4 rounded-2xl bg-slate-950/90 border border-slate-800 text-right space-y-2 text-xs">
              <div className="flex items-center justify-between py-1 border-b border-slate-900">
                <span className="text-slate-300">صلاحية الترخيص الدائم</span>
                <span className="text-emerald-400 font-bold flex items-center gap-1">
                  <Check className="w-3.5 h-3.5" /> مرخص ومفعل
                </span>
              </div>
              <div className="flex items-center justify-between py-1 border-b border-slate-900">
                <span className="text-slate-300">الاتصال بـ Supabase</span>
                <span className="text-emerald-400 font-bold flex items-center gap-1">
                  <Check className="w-3.5 h-3.5" /> متصل ومستقر
                </span>
              </div>
              <div className="flex items-center justify-between py-1 border-b border-slate-900">
                <span className="text-slate-300">جاهزية الجداول والمخطط</span>
                <span className="text-emerald-400 font-bold flex items-center gap-1">
                  <Check className="w-3.5 h-3.5" /> مكتمل (v1)
                </span>
              </div>
              <div className="flex items-center justify-between py-1 border-b border-slate-900">
                <span className="text-slate-300">سجل الشركة والمنظمة</span>
                <span className="text-emerald-400 font-bold flex items-center gap-1">
                  <Check className="w-3.5 h-3.5" /> {verificationResult?.companyName || formCompanyName}
                </span>
              </div>
              <div className="flex items-center justify-between py-1 border-b border-slate-900">
                <span className="text-slate-300">حساب مدير النظام (Owner Admin)</span>
                <span className="text-emerald-400 font-bold flex items-center gap-1">
                  <Check className="w-3.5 h-3.5" /> {verificationResult?.adminUsername || formAdminUsername}
                </span>
              </div>
              <div className="flex items-center justify-between py-1">
                <span className="text-slate-300">نوع الاشتراك</span>
                <span className="text-amber-400 font-bold flex items-center gap-1">
                  <Sparkles className="w-3.5 h-3.5" /> دائم مدى الحياة (Lifetime)
                </span>
              </div>
            </div>

            {/* Credentials Notice Box */}
            <div className="p-3.5 rounded-2xl bg-amber-500/10 border border-amber-500/20 text-amber-300 text-xs flex items-center justify-between text-right">
              <div>
                <span className="font-bold block">اسم المستخدم لتسجيل الدخول:</span>
                <span className="font-mono text-white text-sm font-black" dir="ltr">
                  {verificationResult?.adminUsername || formAdminUsername}
                </span>
              </div>
              <button
                type="button"
                onClick={() => handleCopy(verificationResult?.adminUsername || formAdminUsername, 'adminUser')}
                className="px-3 py-1.5 rounded-xl bg-slate-800 text-amber-400 hover:bg-slate-700 text-xs font-bold flex items-center gap-1 cursor-pointer transition-all"
              >
                {copiedField === 'adminUser' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>نسخ</span>
              </button>
            </div>

            {/* Finish Button */}
            <button
              type="button"
              onClick={onSetupComplete}
              className="w-full py-4 px-6 rounded-2xl font-black text-sm bg-gradient-to-r from-emerald-500 via-emerald-400 to-emerald-500 hover:from-emerald-400 hover:to-emerald-300 text-slate-950 shadow-xl shadow-emerald-500/20 active:scale-[0.99] cursor-pointer transition-all duration-200 flex items-center justify-center gap-2"
            >
              <span>الدخول إلى النظام</span>
              <ArrowLeft className="w-4 h-4 stroke-[2.5]" />
            </button>
          </div>
        )}
      </div>
    </div>
  );
};
