-- ==============================================================================
-- مخطط قاعدة بيانات Supabase (PostgreSQL) لنظام إدارة الفعاليات متعدد الشركات (Multi-Tenancy)
-- ==============================================================================
-- انسخ كامل هذا الملف والصقه في متصفح Supabase في قسم (SQL Editor) ثم اضغط Run.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. إنشاء جدول الشركات (companies)
CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    logo_url TEXT,
    status TEXT NOT NULL DEFAULT 'ACTIVE', -- ACTIVE | INACTIVE
    created_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

-- 2. إنشاء جدول المستخدمين والموظفين (app_users)
CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    temp_password TEXT,
    full_name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'EMPLOYEE', -- SUPER_ADMIN | COMPANY_OWNER | EMPLOYEE
    must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

-- 3. جدول المناسبات (events)
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    date TEXT NOT NULL,
    capacity INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    time TEXT,
    venue TEXT,
    "eventType" TEXT DEFAULT 'wedding',
    created_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    updated_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

-- إضافة عمود company_id لجدول events في حال كان الجدول موجوداً مسبقاً
ALTER TABLE events ADD COLUMN IF NOT EXISTS company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE;

-- 4. جدول الدعوات (invitations)
CREATE TABLE IF NOT EXISTS invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    invitation_number INTEGER NOT NULL,
    token TEXT NOT NULL UNIQUE,
    guest_name TEXT,
    graduate_name TEXT,
    has_name INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'UNUSED', -- UNUSED | USED | CANCELLED
    created_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    used_at TEXT
);

-- 5. جدول سجلات المسح (scan_logs)
CREATE TABLE IF NOT EXISTS scan_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invitation_id BIGINT REFERENCES invitations(id) ON DELETE SET NULL,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    scanned_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    result TEXT NOT NULL, -- ACCEPTED | ALREADY_USED | INVALID | WRONG_EVENT
    device_name TEXT,
    scanned_by_name TEXT,
    scanned_by_id BIGINT REFERENCES app_users(id) ON DELETE SET NULL,
    notes TEXT
);

-- إضافة الأعمدة الإضافية لسجلات المسح إذا كان الجدول منشأ سابقاً
ALTER TABLE scan_logs ADD COLUMN IF NOT EXISTS scanned_by_name TEXT;
ALTER TABLE scan_logs ADD COLUMN IF NOT EXISTS scanned_by_id BIGINT REFERENCES app_users(id) ON DELETE SET NULL;

-- 6. جدول الاشتراكات ونموذج SaaS (tenant_subscriptions)
CREATE TABLE IF NOT EXISTS tenant_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT UNIQUE NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    plan_name TEXT NOT NULL DEFAULT 'Professional',
    billing_cycle TEXT NOT NULL DEFAULT 'monthly', -- monthly | yearly
    status TEXT NOT NULL DEFAULT 'active', -- active | trial | past_due | suspended | cancelled | expired
    start_date TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    renewal_date TEXT NOT NULL DEFAULT to_char(NOW() + interval '1 year', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    expiration_date TEXT NOT NULL DEFAULT to_char(NOW() + interval '1 year', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    payment_status TEXT NOT NULL DEFAULT 'paid',
    created_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    updated_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

-- 7. جدول إعدادات النشر وترخيص التثبيت المخصص
CREATE TABLE IF NOT EXISTS system_deployment_config (
    id BIGINT PRIMARY KEY DEFAULT 1,
    deployment_mode TEXT NOT NULL DEFAULT 'saas', -- saas | dedicated | local_dev
    database_type TEXT NOT NULL DEFAULT 'hosted_supabase',
    database_url TEXT DEFAULT '',
    database_anon_key TEXT DEFAULT '',
    device_name TEXT DEFAULT 'بوابة 1',
    updated_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE IF NOT EXISTS dedicated_licenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,
    company_name TEXT NOT NULL,
    license_key TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'active', -- active | expired | suspended
    issued_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    expires_at TEXT,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS licenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_key_hash TEXT NOT NULL UNIQUE,
    company_name TEXT NOT NULL,
    license_type TEXT NOT NULL DEFAULT 'PERPETUAL', -- PERPETUAL | SUBSCRIPTION
    status TEXT NOT NULL DEFAULT 'active', -- active | revoked | expired | suspended
    max_devices INTEGER NOT NULL DEFAULT 1,
    expires_at TEXT,
    created_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE IF NOT EXISTS license_activations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_id BIGINT NOT NULL REFERENCES licenses(id) ON DELETE CASCADE,
    device_id_hash TEXT NOT NULL,
    device_name TEXT,
    activated_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    last_seen_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    deactivated_at TEXT
);

-- 7b. جدول تتبع إصدارات مخطط قاعدة البيانات والترقيات (database_schema_version)
CREATE TABLE IF NOT EXISTS database_schema_version (
    version INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    applied_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

-- 8. إنشاء الفهارس السريعة
CREATE INDEX IF NOT EXISTS idx_app_users_username ON app_users(username);
CREATE INDEX IF NOT EXISTS idx_app_users_company ON app_users(company_id);
CREATE INDEX IF NOT EXISTS idx_events_company ON events(company_id);
CREATE INDEX IF NOT EXISTS idx_invitations_token ON invitations(token);
CREATE INDEX IF NOT EXISTS idx_invitations_event ON invitations(event_id);
CREATE INDEX IF NOT EXISTS idx_invitations_status ON invitations(status);
CREATE INDEX IF NOT EXISTS idx_scan_logs_event ON scan_logs(event_id);
CREATE INDEX IF NOT EXISTS idx_scan_logs_scanned_at ON scan_logs(scanned_at DESC);
CREATE INDEX IF NOT EXISTS idx_subscriptions_company ON tenant_subscriptions(company_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON tenant_subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_licenses_hash ON licenses(license_key_hash);
CREATE INDEX IF NOT EXISTS idx_license_activations_license ON license_activations(license_id);
CREATE INDEX IF NOT EXISTS idx_license_activations_device ON license_activations(device_id_hash);


-- 9. إنشاء شركة افتراضية واشتراك وحساب الأدمن العام (إذا لم تكن موجودة)
DO $$
DECLARE
    v_comp_id BIGINT;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM companies LIMIT 1) THEN
        INSERT INTO companies (name, status)
        VALUES ('الشركة الافتراضية', 'ACTIVE')
        RETURNING id INTO v_comp_id;

        -- ربط أي مناسبات سابقة ليس لها شركة بالشركة الافتراضية
        UPDATE events SET company_id = v_comp_id WHERE company_id IS NULL;
    ELSE
        SELECT id INTO v_comp_id FROM companies LIMIT 1;
        UPDATE events SET company_id = v_comp_id WHERE company_id IS NULL;
    END IF;

    -- إضافة اشتراك تلقائي للشركة
    IF NOT EXISTS (SELECT 1 FROM tenant_subscriptions WHERE company_id = v_comp_id) THEN
        INSERT INTO tenant_subscriptions (company_id, plan_name, billing_cycle, status, start_date, renewal_date, expiration_date, payment_status)
        VALUES (v_comp_id, 'Professional', 'yearly', 'active', to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), to_char(NOW() + interval '1 year', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), to_char(NOW() + interval '1 year', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), 'paid');
    END IF;

    -- إضافة حساب الأدمن العام (admin / admin123)
    IF NOT EXISTS (SELECT 1 FROM app_users WHERE username = 'admin') THEN
        INSERT INTO app_users (company_id, username, password_hash, temp_password, full_name, role, must_change_password)
        VALUES (NULL, 'admin', encode(digest('admin123', 'sha256'), 'hex'), NULL, 'مدير النظام العام', 'SUPER_ADMIN', FALSE);
    END IF;
END $$;

-- 10. إجراء تسجيل الدخول الموحد لجميع المنصات مع فحص الاشتراك والحالة (Login RPC)
CREATE OR REPLACE FUNCTION login_app_user(
    p_username TEXT,
    p_password TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_user RECORD;
    v_input_hash TEXT;
BEGIN
    v_input_hash := encode(digest(TRIM(p_password), 'sha256'), 'hex');

    SELECT u.*, c.name as comp_name, c.logo_url as comp_logo, c.status as comp_status,
           s.status as sub_status, s.expiration_date as sub_expiration, s.plan_name as sub_plan
    INTO v_user
    FROM app_users u
    LEFT JOIN companies c ON u.company_id = c.id
    LEFT JOIN tenant_subscriptions s ON s.company_id = c.id
    WHERE LOWER(TRIM(u.username)) = LOWER(TRIM(p_username));

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'error', 'اسم المستخدم غير موجود');
    END IF;

    -- التحقق من كلمة المرور: إما تطابق الهاش أو كلمة المرور المؤقتة المسجلة
    IF v_user.password_hash <> v_input_hash AND (v_user.temp_password IS NULL OR v_user.temp_password <> TRIM(p_password)) THEN
        RETURN jsonb_build_object('success', false, 'error', 'كلمة المرور غير صحيحة');
    END IF;

    -- التحقق من حالة الشركة لغير السوبر أدمن
    IF v_user.role <> 'SUPER_ADMIN' THEN
        IF v_user.comp_status = 'SUSPENDED' OR v_user.comp_status = 'INACTIVE' THEN
            RETURN jsonb_build_object('success', false, 'error', 'يرجى التواصل مع الإدارة');
        END IF;

        -- التحقق من حالة الاشتراك
        IF v_user.sub_status IS NOT NULL AND (v_user.sub_status = 'suspended' OR v_user.sub_status = 'expired' OR v_user.sub_status = 'cancelled') THEN
            RETURN jsonb_build_object('success', false, 'error', 'تم تعليق الاشتراك - يرجى التواصل مع الإدارة لتجديد الاشتراك');
        END IF;
    END IF;

    RETURN jsonb_build_object(
        'success', true,
        'user', jsonb_build_object(
            'id', v_user.id,
            'company_id', v_user.company_id,
            'username', v_user.username,
            'full_name', v_user.full_name,
            'role', v_user.role,
            'must_change_password', v_user.must_change_password,
            'temp_password', v_user.temp_password,
            'company_name', v_user.comp_name,
            'company_logo', v_user.comp_logo,
            'company_status', v_user.comp_status,
            'subscription_status', v_user.sub_status
        )
    );
END;
$$;

-- 9. إجراء تغيير كلمة المرور وإلغاء كلمة المرور المؤقتة
CREATE OR REPLACE FUNCTION change_app_user_password(
    p_user_id BIGINT,
    p_new_password TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_new_hash TEXT;
BEGIN
    IF LENGTH(TRIM(p_new_password)) < 4 THEN
        RETURN jsonb_build_object('success', false, 'error', 'كلمة المرور يجب أن لا تقل عن 4 خانات');
    END IF;

    v_new_hash := encode(digest(TRIM(p_new_password), 'sha256'), 'hex');

    UPDATE app_users
    SET password_hash = v_new_hash,
        temp_password = NULL,
        must_change_password = FALSE
    WHERE id = p_user_id;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'error', 'المستخدم غير موجود');
    END IF;

    RETURN jsonb_build_object('success', true);
END;
$$;

-- 10. الدالة الذرية المطورة لفحص وتأكيد الدخول وتسجيل اسم الموظف
CREATE OR REPLACE FUNCTION check_in_atomic(
    p_token TEXT,
    p_event_id BIGINT,
    p_device_name TEXT DEFAULT NULL,
    p_scanned_by TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_inv RECORD;
    v_now TEXT := to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
    v_prev_scan RECORD;
    v_scanner_label TEXT := COALESCE(NULLIF(TRIM(p_scanned_by), ''), 'الموظف المسؤول');
BEGIN
    -- قفل الصف فورياً لمنع أي جهاز آخر من التعديل عليه في نفس اللحظة (Row-level Lock)
    SELECT * INTO v_inv
    FROM invitations
    WHERE token = TRIM(p_token)
    FOR UPDATE;

    -- 1. الرمز غير موجود بتاتاً
    IF NOT FOUND THEN
        INSERT INTO scan_logs (invitation_id, event_id, scanned_at, result, device_name, scanned_by_name, notes)
        VALUES (NULL, p_event_id, v_now, 'INVALID', p_device_name, v_scanner_label, 'رمز QR غير معروف: ' || SUBSTRING(p_token, 1, 15));
        
        RETURN jsonb_build_object(
            'success', false,
            'result', 'INVALID',
            'message', 'رمز الدعوة غير صالح أو غير موجود في النظام!'
        );
    END IF;

    -- 2. الرمز تابع لمناسبة أخرى
    IF v_inv.event_id <> p_event_id THEN
        INSERT INTO scan_logs (invitation_id, event_id, scanned_at, result, device_name, scanned_by_name, notes)
        VALUES (v_inv.id, p_event_id, v_now, 'WRONG_EVENT', p_device_name, v_scanner_label, 'دعوة تابعة لمناسبة أخرى');

        RETURN jsonb_build_object(
            'success', false,
            'result', 'WRONG_EVENT',
            'message', 'هذه الدعوة مخصصة لمناسبة أخرى ولا تتبع هذه المناسبة!',
            'guestName', v_inv.guest_name,
            'invitationNumber', v_inv.invitation_number
        );
    END IF;

    -- 3. الرمز مستخدم مسبقاً (جلب من قام بالمسح السابق)
    IF v_inv.status = 'USED' THEN
        SELECT scanned_by_name, scanned_at INTO v_prev_scan
        FROM scan_logs
        WHERE invitation_id = v_inv.id AND result = 'ACCEPTED'
        ORDER BY id DESC
        LIMIT 1;

        INSERT INTO scan_logs (invitation_id, event_id, scanned_at, result, device_name, scanned_by_name, notes)
        VALUES (
            v_inv.id, 
            p_event_id, 
            v_now, 
            'ALREADY_USED', 
            p_device_name, 
            v_scanner_label, 
            'محاولة دخول مكررة لدعوة ممسوحة سابقاً بواسطة: ' || COALESCE(v_prev_scan.scanned_by_name, 'غير محدد')
        );

        RETURN jsonb_build_object(
            'success', false,
            'result', 'ALREADY_USED',
            'message', 'تم استخدام هذه الدعوة مسبقاً! يرجى منع الدخول.',
            'previousUsedAt', COALESCE(v_prev_scan.scanned_at, v_inv.used_at),
            'scannedBy', v_prev_scan.scanned_by_name,
            'guestName', v_inv.guest_name,
            'invitationNumber', v_inv.invitation_number
        );
    END IF;

    -- 4. الرمز ملغي
    IF v_inv.status = 'CANCELLED' THEN
        INSERT INTO scan_logs (invitation_id, event_id, scanned_at, result, device_name, scanned_by_name, notes)
        VALUES (v_inv.id, p_event_id, v_now, 'INVALID', p_device_name, v_scanner_label, 'دعوة ملغاة');

        RETURN jsonb_build_object(
            'success', false,
            'result', 'INVALID',
            'message', 'هذه الدعوة تم إلغاؤها من قبل الإدارة!',
            'guestName', v_inv.guest_name,
            'invitationNumber', v_inv.invitation_number
        );
    END IF;

    -- 5. رمز سليم وغير مستخدم -> تحديث ذرّي فوري
    UPDATE invitations
    SET status = 'USED', used_at = v_now
    WHERE id = v_inv.id AND status = 'UNUSED';

    -- تسجيل الحركة في السجلات مع اسم الموظف
    INSERT INTO scan_logs (invitation_id, event_id, scanned_at, result, device_name, scanned_by_name, notes)
    VALUES (v_inv.id, p_event_id, v_now, 'ACCEPTED', p_device_name, v_scanner_label, 'دخول مصرح - الدعوة #' || v_inv.invitation_number);

    RETURN jsonb_build_object(
        'success', true,
        'result', 'ACCEPTED',
        'message', 'تم قبول الدخول بنجاح. أهلاً وسهلاً!',
        'guestName', v_inv.guest_name,
        'invitationNumber', v_inv.invitation_number,
        'scannedBy', v_scanner_label,
        'used_at', v_now
    );
END;
$$;

-- 11. دالة تصفير الباركودات المستخدمة
CREATE OR REPLACE FUNCTION reset_used_invitations(p_event_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM invitations WHERE event_id = p_event_id AND status = 'USED';

    UPDATE invitations 
    SET status = 'UNUSED', used_at = NULL 
    WHERE event_id = p_event_id AND status = 'USED';

    DELETE FROM scan_logs WHERE event_id = p_event_id;

    RETURN jsonb_build_object('success', true, 'resetCount', v_count);
END;
$$;

-- 12. تفعيل سياسات الأمان RLS
ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE scan_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_deployment_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE dedicated_licenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE database_schema_version ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for companies" ON companies;
CREATE POLICY "Allow all for companies" ON companies FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for app_users" ON app_users;
CREATE POLICY "Allow all for app_users" ON app_users FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for events" ON events;
CREATE POLICY "Allow all for events" ON events FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for invitations" ON invitations;
CREATE POLICY "Allow all for invitations" ON invitations FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for scan_logs" ON scan_logs;
CREATE POLICY "Allow all for scan_logs" ON scan_logs FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for tenant_subscriptions" ON tenant_subscriptions;
CREATE POLICY "Allow all for tenant_subscriptions" ON tenant_subscriptions FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for system_deployment_config" ON system_deployment_config;
CREATE POLICY "Allow all for system_deployment_config" ON system_deployment_config FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for dedicated_licenses" ON dedicated_licenses;
CREATE POLICY "Allow all for dedicated_licenses" ON dedicated_licenses FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for database_schema_version" ON database_schema_version;
CREATE POLICY "Allow all for database_schema_version" ON database_schema_version FOR ALL USING (true) WITH CHECK (true);

INSERT INTO database_schema_version (version, name)
VALUES (1, 'v1_initial_core_schema')
ON CONFLICT (version) DO NOTHING;

-- 13. تفعيل ميزة البث الفوري Realtime
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'invitations'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE invitations;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'scan_logs'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE scan_logs;
    END IF;
END $$;

-- 15. دالة تغيير كلمة المرور للمستخدم (تصفير المؤقتة وفرض الحفظ)
CREATE OR REPLACE FUNCTION change_app_user_password(p_user_id BIGINT, p_new_password TEXT)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_new_hash TEXT;
BEGIN
    IF LENGTH(TRIM(p_new_password)) < 4 THEN
        RETURN jsonb_build_object('success', false, 'error', 'كلمة المرور يجب ألا تقل عن 4 خانات');
    END IF;

    v_new_hash := encode(digest(p_new_password, 'sha256'), 'hex');

    UPDATE app_users
    SET password_hash = v_new_hash,
        temp_password = NULL,
        must_change_password = FALSE
    WHERE id = p_user_id;

    RETURN jsonb_build_object('success', true);
END;
$$;

-- 16. إنشاء وتثبيت حساب الأدمن العام (Ryan_osama)
INSERT INTO app_users (company_id, username, password_hash, temp_password, full_name, role, must_change_password)
VALUES (
    NULL,
    'Ryan_osama',
    '4ee8de66d65e2d776b110e2b53bc022e96b26cc90cec659892ddc05cbce0dbad',
    NULL,
    'مدير النظام (Ryan Osama)',
    'SUPER_ADMIN',
    FALSE
)
ON CONFLICT (username) DO UPDATE
SET password_hash = EXCLUDED.password_hash,
    temp_password = NULL,
    must_change_password = FALSE;
