-- ==============================================================================
-- مخطط قاعدة بيانات Supabase (PostgreSQL) لنظام إدارة الدعوات ومسح الباركود
-- ==============================================================================
-- انسخ كامل هذا الملف والصقه في متصفح Supabase في قسم (SQL Editor) ثم اضغط Run.

-- 1. إنشاء جدول المناسبات (events)
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    date TEXT NOT NULL,
    capacity INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    time TEXT,
    venue TEXT,
    "eventType" TEXT DEFAULT 'wedding',
    created_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    updated_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

-- 2. إنشاء جدول الدعوات (invitations)
CREATE TABLE IF NOT EXISTS invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    invitation_number INTEGER NOT NULL,
    token TEXT NOT NULL UNIQUE,
    guest_name TEXT,
    graduate_name TEXT,
    has_name INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'UNUSED', -- UNUSED | USED | CANCELLED
    created_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    used_at TEXT
);

-- 3. إنشاء جدول سجلات المسح (scan_logs)
CREATE TABLE IF NOT EXISTS scan_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invitation_id BIGINT REFERENCES invitations(id) ON DELETE SET NULL,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    scanned_at TEXT NOT NULL DEFAULT to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    result TEXT NOT NULL, -- ACCEPTED | ALREADY_USED | INVALID | WRONG_EVENT
    device_name TEXT,
    notes TEXT
);

-- 4. إنشاء الفهارس السريعة لضمان استجابة فورية (أقل من 30ms)
CREATE INDEX IF NOT EXISTS idx_invitations_token ON invitations(token);
CREATE INDEX IF NOT EXISTS idx_invitations_event ON invitations(event_id);
CREATE INDEX IF NOT EXISTS idx_invitations_status ON invitations(status);
CREATE INDEX IF NOT EXISTS idx_scan_logs_event ON scan_logs(event_id);
CREATE INDEX IF NOT EXISTS idx_scan_logs_scanned_at ON scan_logs(scanned_at DESC);

-- 5. الدالة الذرية فائقة الأمان والسرعة لمنع التكرار (Atomic Check-in Procedure)
-- تضمن بنسبة 100% أنه حتى لو مسح جهازان نفس الباركود في نفس الميلي ثانية، يقبل واحد فقط ويرفض الآخر.
CREATE OR REPLACE FUNCTION check_in_atomic(
    p_token TEXT,
    p_event_id BIGINT,
    p_device_name TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_inv RECORD;
    v_now TEXT := to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
BEGIN
    -- قفل الصف فورياً لمنع أي جهاز آخر من التعديل عليه في نفس اللحظة (Row-level Lock)
    SELECT * INTO v_inv
    FROM invitations
    WHERE token = TRIM(p_token)
    FOR UPDATE;

    -- 1. الرمز غير موجود بتاتاً
    IF NOT FOUND THEN
        INSERT INTO scan_logs (invitation_id, event_id, scanned_at, result, device_name, notes)
        VALUES (NULL, p_event_id, v_now, 'INVALID', p_device_name, 'رمز QR غير معروف: ' || SUBSTRING(p_token, 1, 15));
        
        RETURN jsonb_build_object(
            'success', false,
            'result', 'INVALID',
            'message', 'رمز الدعوة غير صالح أو غير موجود في النظام!'
        );
    END IF;

    -- 2. الرمز تابع لمناسبة أخرى
    IF v_inv.event_id <> p_event_id THEN
        INSERT INTO scan_logs (invitation_id, event_id, scanned_at, result, device_name, notes)
        VALUES (v_inv.id, p_event_id, v_now, 'WRONG_EVENT', p_device_name, 'دعوة تابعة لمناسبة أخرى');

        RETURN jsonb_build_object(
            'success', false,
            'result', 'WRONG_EVENT',
            'message', 'هذه الدعوة مخصصة لمناسبة أخرى ولا تتبع هذه المناسبة!',
            'guestName', v_inv.guest_name,
            'invitationNumber', v_inv.invitation_number
        );
    END IF;

    -- 3. الرمز مستخدم مسبقاً
    IF v_inv.status = 'USED' THEN
        INSERT INTO scan_logs (invitation_id, event_id, scanned_at, result, device_name, notes)
        VALUES (v_inv.id, p_event_id, v_now, 'ALREADY_USED', p_device_name, 'محاولة دخول مكررة لدعوة مستخدمة مسبقاً');

        RETURN jsonb_build_object(
            'success', false,
            'result', 'ALREADY_USED',
            'message', 'تم استخدام هذه الدعوة مسبقاً! يرجى منع الدخول.',
            'previousUsedAt', v_inv.used_at,
            'guestName', v_inv.guest_name,
            'invitationNumber', v_inv.invitation_number
        );
    END IF;

    -- 4. الرمز ملغي
    IF v_inv.status = 'CANCELLED' THEN
        INSERT INTO scan_logs (invitation_id, event_id, scanned_at, result, device_name, notes)
        VALUES (v_inv.id, p_event_id, v_now, 'INVALID', p_device_name, 'دعوة ملغاة');

        RETURN jsonb_build_object(
            'success', false,
            'result', 'INVALID',
            'message', 'هذه الدعوة تم إلغاؤها من قبل الإدارة!',
            'guestName', v_inv.guest_name,
            'invitationNumber', v_inv.invitation_number
        );
    END IF;

    -- 5. رمز سليم وغير مستخدم -> تحديث ذرّي فوري
    UPDATE invitations
    SET status = 'USED', used_at = v_now
    WHERE id = v_inv.id AND status = 'UNUSED';

    -- تسجيل الحركة في السجلات
    INSERT INTO scan_logs (invitation_id, event_id, scanned_at, result, device_name, notes)
    VALUES (v_inv.id, p_event_id, v_now, 'ACCEPTED', p_device_name, 'دخول مصرح - الدعوة #' || v_inv.invitation_number);

    RETURN jsonb_build_object(
        'success', true,
        'result', 'ACCEPTED',
        'message', 'تم قبول الدخول بنجاح. أهلاً وسهلاً!',
        'guestName', v_inv.guest_name,
        'invitationNumber', v_inv.invitation_number,
        'used_at', v_now
    );
END;
$$;

-- 6. تفعيل سياسات الأمان وتصاريح الوصول عبر مفتاح Anon
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE scan_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for events" ON events;
CREATE POLICY "Allow all for events" ON events FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for invitations" ON invitations;
CREATE POLICY "Allow all for invitations" ON invitations FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for scan_logs" ON scan_logs;
CREATE POLICY "Allow all for scan_logs" ON scan_logs FOR ALL USING (true) WITH CHECK (true);

-- 7. تفعيل ميزة البث الفوري Realtime
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'invitations'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE invitations;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'scan_logs'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE scan_logs;
    END IF;
END $$;
